spring:
  application:
    name: provider

server:
  port: 8081
  #servlet:
    #path: /provider

eureka:
  instance:
    #hostname: 127.0.0.1
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.hostname}:${server.port}
    lease-expiration-duration-in-seconds: 60
    lease-renewal-interval-in-seconds: 30
  client:
    service-url:
      defaultZone: http://127.0.0.1:1111/eureka

